### ISSUE TITLE
Build error in google/internal/externalaccount

### ISSUE THREAD

**Issue by yath** [golang/oauth2#628]
Hi,

the `externalaccount` package (which is a dependency of `oauth2l` fails to build):

```
$ go get github.com/google/oauth2l/vendor/golang.org/x/oauth2/google/internal/externalaccount
# github.com/google/oauth2l/vendor/golang.org/x/oauth2/google/internal/externalaccount
go/src/github.com/google/oauth2l/vendor/golang.org/x/oauth2/google/internal/externalaccount/executablecredsource.go:124:39: exitError.ExitCode undefined (type *exec.ExitError has no field or method ExitCode)
go/src/github.com/google/oauth2l/vendor/golang.org/x/oauth2/google/internal/externalaccount/executablecredsource.go:256:15: undefined: io.ReadAll
```

This is using `go version go1.11.6 linux/amd64`.

**Comment by yath** [comment]
Nevermind, it works with Go 1.20, sorry.
